kind: pipeline
type: kubernetes
name: default

resources:
  requests:
    cpu: 1000
    memory: 1000Mib

steps:
- name: backend
  image: golang
  commands:
  - sleep 1000
  resources:
    limits:
      cpu: 100
      memory: 50Mib
    requests:
      cpu: 300
      memory: 300Mib
      
- name: docker
  image: plugins/kaniko
  settings:
    repo: shubham149/test
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: Dockerfile
    tags: vx1.0,latest
    registry: "https://index.docker.io/v1/"
  resources:
    limits:
      cpu: 100
      memory: 100Mib
    requests:
      cpu: 400
      memory: 400Mib
