kind: pipeline
type: kubernetes
name: default

resources:
  requests:
    cpu: 1000
    memory: 1000Mib
  limits:
    cpu: 10
    memory: 100Mib

steps:
- name: backend
  image: golang
  commands:
  - sleep 1
  resources:
    limits:
      cpu: 10
      memory: 5Mib
   
